"""float in complaint

Revision ID: 95814307a852
Revises: 065208c98359
Create Date: 2022-02-24 23:36:19.504580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95814307a852'
down_revision = '065208c98359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
