"""initial

Revision ID: f072b22cdca5
Revises: d789ef178150
Create Date: 2022-02-24 15:52:12.537153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f072b22cdca5'
down_revision = 'd789ef178150'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
